### PR TITLE
FEAT : Added speech-to-text using Web-Speech-Api, FIX : Added Prettier Formatting

### PR DESCRIPTION
**Pull request by MohammedZuhairAhmed**
FIX : Added Prettier Formatting

### CODE REVIEW

**Comment by jakobhoeg** [comment]
Hey, @MohammedZuhairAhmed.

Thanks for your contribution. However, I think you'll need to work a bit on the logic.
Right now it's only allowing for voice input? I can't write anything in the input field anymore. I'd rather the logic being that when a microphone button is pressed, it listens to voice input and transcribes it into the input field.
Besides that, the entire div is flickering in height/width changes when I hover over the chat-bottombar div.

Also I do appreciate the prettier formatting commit.

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg,

The current logic is like this.

When we click on the microphone button, the placeholder is updated to 'listening...', and as we speak the same is displayed in the Text area.

Then after this we need to disable the microphone by clicking on that button, and send the message.

Whenever the microphone is enabled, I have disabled the Text area and when it's disabled you can normally make use of text area with keyboard input as usual

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg,

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg,


Another notable logic regarding the microphone button is,


Let's say the user has typed something in the text area for e.g. "hello, " , then the user may click to provide the remaining input i.e. "How are you" by microphone.

So when this happens the current input value "hello, " will be overwritten **not appended** and will result in only "How are you".


This is how the gemini voice input also works so I implemented it in this fashion.

----
If you need append behaviour rather than overwrite, then I can work on this logic also

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg , could you answer to my questions and get the expectations clarified to work on it?

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg ,

Any updates on what changes that need to be done?

**Comment by MohammedZuhairAhmed** [comment]
Hello @jakobhoeg ,

Could you tell me the changes that needs to be done after reviewing once

**Comment by jakobhoeg** [comment]
Hey, @MohammedZuhairAhmed.
There are a ton of merge conflicts because you've decided to format the entire repo. 
Can you please undo that commit? Then I'll take a look.

**Pull request closed without merging**
